### ISSUE TITLE
Pequeño fallo 1

### ISSUE THREAD

**Issue by RaulRubioBressel** [surtich/todo-list-daw2#1]
El campo "Clear completed" no se pone a cero cuando marcas varios Todos y los desmarcas; la solución consiste en añadir  "  clearCompleted.innerHTML = "Clear completed (" + (TODO_APP.countTodos() - TODO_APP.itemsLeft()) + ")";   "  en la "function render" del archivo "init.js" en el "else" cuando " clearCompleted.style.display = 'none'; ".

**Comment by surtich** [comment]
Vale, 

Como te dije, no lo considero un fallo ya que se oculta el componente y, por lo tanto, da igual el valor que tenga.

Pero, de todas formas, si lo solucionas, te doy +0,25 puntos en la nota del examen.

![image](https://f.cloud.github.com/assets/2861070/1499297/fdf5ec02-4854-11e3-8674-107e7c751138.png)

**Comment by RaulRubioBressel** [comment]
La solución ya la puse; en esa parte del código en el else añadir 

Clear completed (" + (TODO_APP.countTodos() - TODO_APP.itemsLeft()) + ")";

justo debajo de 

clearCompleted.style.display = 'none';

**Comment by surtich** [comment]
Ya, pero haz lo que te digo del fork + pull request. Como te decía ayer, quiero que trabajéis de una forma profesional. No con el clásico copy + paste de toda la vida.
